# This is a basic workflow to help you get started with Actions

name: Build for Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      # Cache library for faster builds
      - name: Cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Github-Actions-Pipeline-Android
          restore-keys: |
            Library-Github-Actions-Pipeline-Library

      # Run tests. Set tests to run parallel to build, but before upload
      
      # Build application
      - name: unity-windows-build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: '2022.3.14f1'
          targetPlatform: 'StandaloneWindows'

      # Upload artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Referenced DLLs
          # This is unity-builder's default build location
          path: build
